"""empty message

Revision ID: 74004fe0896a
Revises: 35410e7e1b2d
Create Date: 2025-06-24 23:18:07.966585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

temp_uid_placeholder = 'hdrJOPKflbhaEFKE6tT6Jmk8gfz1'

# revision identifiers, used by Alembic.
revision: str = '74004fe0896a'
down_revision: Union[str, None] = '35410e7e1b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_uid', sa.String(), nullable=False, server_default=temp_uid_placeholder))
    op.create_index(op.f('ix_projects_owner_uid'), 'projects', ['owner_uid'], unique=False)
    op.add_column('tasks', sa.Column('owner_uid', sa.String(), nullable=False, server_default=temp_uid_placeholder))
    op.create_index(op.f('ix_tasks_owner_uid'), 'tasks', ['owner_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_owner_uid'), table_name='tasks')
    op.drop_column('tasks', 'owner_uid')
    op.drop_index(op.f('ix_projects_owner_uid'), table_name='projects')
    op.drop_column('projects', 'owner_uid')
    # ### end Alembic commands ###
